openapi: 3.0.0
info:
  title: API do Projeto
  version: 1.0.0
paths:
  /api/login:
    post:
      summary: Realiza login do usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
              required:
                - email
                - password
            example:
              email: "user@email.com"
              password: "123456"
      responses:
        '200':
          description: Login bem-sucedido
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  email:
                    type: string
                  token:
                    type: string
              example:
                id: 1
                name: "Alice"
                email: "alice@email.com"
                token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"
        '422':
          description: Credenciais inválidas
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  errors:
                    type: object
                    additionalProperties:
                      type: array
                      items:
                        type: string
              example:
                message: "Os dados informados são inválidos."
                errors:
                  email: ["Usuário não encontrado. Verifique suas credenciais de login e senha."]
  /api/password/forgot:
    post:
      summary: Recuperação de senha
      description: Envia um e-mail com instruções de recuperação de senha para o usuário, caso o e-mail esteja cadastrado.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
              required:
                - email
            example:
              email: "user@email.com"
      responses:
        '200':
          description: E-mail de recuperação enviado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: "E-mail de recuperação enviado com sucesso."
        '404':
          description: Usuário não encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              example:
                message: "Usuário não encontrado."
